version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    links:
      - postgres
      - redis
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=gympoint
      - POSTGRES_USER=gympoint
      - POSTGRES_DB=gympoint
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
